# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree_search_rcpp <- function(X, Y, depth, min_node_size, datatype, find_reward_ub, find_dummy_split_reward, use_last_rewards, use_cutoffs, use_cache, exploit_binaryvars) {
    .Call('_fastpolicytree_tree_search_rcpp', PACKAGE = 'fastpolicytree', X, Y, depth, min_node_size, datatype, find_reward_ub, find_dummy_split_reward, use_last_rewards, use_cutoffs, use_cache, exploit_binaryvars)
}

githash_rcpp <- function() {
    .Call('_fastpolicytree_githash_rcpp', PACKAGE = 'fastpolicytree')
}

